### ISSUE TITLE
Android Studio failing to resolve dependancy

### ISSUE THREAD

**Issue by devnullpointer** [LukeHagar/plexjava#5]
In my app:build.gradle I added the
    implementation 'lukehagar.plexapi:plexapi:0.1.1'

and when I sync my project I get:
Failed to resolve: lukehagar.plexapi:plexapi:0.1.1
Show in Project Structure dialog
Affected Modules: app

It's the only dependency that is not resolving.

**Comment by LukasParke** [comment]
Hey Bill,

I haven’t actually published this package anywhere yet.

I’ll look to get that completed soon and share it with you.

**Comment by devnullpointer** [comment]
Thanks mate. Looking forward to it.

**Comment by LukasParke** [comment]
@devnullpointer This is now published!

Readme should have all the info needed, let me know if you have any specific questions.
